# Generated by Django 5.2.1 on 2025-06-02 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha2_code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('common_name', models.CharField(blank=True, max_length=128)),
                ('region', models.CharField(max_length=64)),
                ('subregion', models.CharField(blank=True, max_length=64)),
                ('capital', models.CharField(blank=True, max_length=64)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('flag_png', models.URLField(blank=True)),
                ('flag_svg', models.URLField(blank=True)),
                ('coat_of_arms_png', models.URLField(blank=True)),
                ('coat_of_arms_svg', models.URLField(blank=True)),
                ('borders', models.TextField(blank=True)),
                ('independent', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('request_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NameCountryProbability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_probabilities', to='names.country')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_probabilities', to='names.name')),
            ],
            options={
                'unique_together': {('name', 'country')},
            },
        ),
    ]
